### ISSUE TITLE
manuscript - eliminate dependency on `covidHubUtils::as_covid_hub_forecasts`

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubEnsembles#46]
I wonder if we can just add a quick custom function to convert the forecast format for purpose of this vignette.  It could be shorter/less careful than the one that's in covidHubUtils.  Then we could remove the dependency on covidHubUtils from the vignette.

**Comment by lshandross** [comment]
While we could eliminate the dependency by doing this, I was actually wondering if that something we want to do. My slight hesitance has to do with the fact that `covidHubUtils::score_forecasts` was used for scoring. We could get away with removing the dependencies since I was loading in the already-scored forecasts into the vignette file, but I don't know if it's better practice to keep in the `covidHubUtils` package given that we're technically using two functions from it for the analysis.

**Comment by nickreich** [comment]
My feeling is that given that we don't expect to continue to maintain covidHubUtils to quite the same standard that we do for this package, AND that it's better to have fewer dependencies, I'd advocate for doing what we can to drop the dependency.
